# Generated by Django 2.0.6 on 2018-07-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menumaker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
