# Generated by Django 2.0.6 on 2018-07-05 14:50

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menumaker_app', '0002_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Ingredient', max_length=100, null=True), default=['Ingredient'], size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(default='Cuisine', max_length=30),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='Instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'Dale': 'True'}),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
