# Generated by Django 2.0.6 on 2018-07-08 09:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menumaker_app', '0003_auto_20180705_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
