# Generated by Django 2.0.6 on 2018-07-08 13:58

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menumaker_app', '0006_auto_20180708_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'Dale': 'False', 'Isabelle': 'False', 'Jennifer': 'False', 'Parker': 'False'}),
        ),
    ]
