# Generated by Django 2.0.6 on 2018-07-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menumaker_app', '0007_auto_20180708_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
